DATASET_PATH = "fabric_dataset"
MODEL_RESNET18_NAME = "resnet18"
MODEL_RESNET50_NAME = "resnet50"
MODEL_RESNET18_PATH = "classifier_resnet18.pth"
MODEL_RESNET50_PATH = "classifier_resnet50.pth"
TRAIN_DATASET_PATH = "train_dataset"
VALIDATION_DATASET_PATH = "validation_dataset"
TEST_DATASET_PATH = "test_dataset"
CLASSES = ("normal", "defective")
IMAGE_SIZE = 224
BATCH_SIZE = 8
EPOCHS = 50
LEARNING_RATE = 0.001
EARLY_STOPPING = 5